export type Sector =
  | "Servicii Locale"
  | "Sănătate & Medical"
  | "Educație & Instituții"
  | "Turism & Ospitalitate"
  | "Tech & Software"
  | "E-Commerce"
  | "Creativ & Media"
  | "Industrie & Producție";

export interface TemplateCategory {
  slug: string;
  name: string;
  sector: Sector;
  emoji: string;
  accent: string;
  accentFg: "white" | "black";
  bgLight: string;
  bgDark: string;
  textDark: string;
  headline: string;
  tagline: string;
  services: [string, string, string];
  price: string;
  cta: string;
}

export const categories: TemplateCategory[] = [
  /* ─── SERVICII LOCALE ─────────────────────────────────────────────── */
  {
    slug: "florarie",
    name: "Florărie",
    sector: "Servicii Locale",
    emoji: "🌸",
    accent: "#e8688a",
    accentFg: "white",
    bgLight: "#fdf2f5",
    bgDark: "#2d0a14",
    textDark: "#3d0a14",
    headline: "Flori pentru fiecare moment.",
    tagline: "Buchete, aranjamente florale și livrare rapidă în oraș.",
    services: ["Buchete Personalizate", "Aranjamente Nuntă & Evenimente", "Livrare la Domiciliu"],
    price: "de la 80 lei",
    cta: "Comandă acum",
  },
  {
    slug: "cabinet-medical",
    name: "Cabinet Medical",
    sector: "Servicii Locale",
    emoji: "🩺",
    accent: "#2563eb",
    accentFg: "white",
    bgLight: "#eff6ff",
    bgDark: "#0c1a3a",
    textDark: "#0c1a3a",
    headline: "Sănătatea ta, prioritatea noastră.",
    tagline: "Consultații, diagnostic și tratament profesional.",
    services: ["Consultații Medicale", "Investigații Paraclinice", "Tratamente Specializate"],
    price: "Consultație de la 150 lei",
    cta: "Programează-te",
  },
  {
    slug: "stomatologie",
    name: "Stomatologie",
    sector: "Servicii Locale",
    emoji: "🦷",
    accent: "#0d9488",
    accentFg: "white",
    bgLight: "#f0fdfa",
    bgDark: "#042f2e",
    textDark: "#042f2e",
    headline: "Zâmbetul tău, perfect.",
    tagline: "Tratamente dentare moderne, estetică dentară și implanturi.",
    services: ["Estetică Dentară", "Implanturi Dentare", "Ortodonție Invizibilă"],
    price: "Consultație gratuită",
    cta: "Rezervă o programare",
  },
  {
    slug: "farmacie",
    name: "Farmacie",
    sector: "Servicii Locale",
    emoji: "💊",
    accent: "#16a34a",
    accentFg: "white",
    bgLight: "#f0fdf4",
    bgDark: "#052e16",
    textDark: "#052e16",
    headline: "Sănătate la un pas distanță.",
    tagline: "Medicamente, suplimente și produse naturiste. Livrare rapidă.",
    services: ["Medicamente cu & fără Rețetă", "Produse Naturiste & BIO", "Livrare la Domiciliu"],
    price: "Livrare gratuită la 200+ lei",
    cta: "Comandă online",
  },
  {
    slug: "fitness",
    name: "Fitness & Sală",
    sector: "Servicii Locale",
    emoji: "💪",
    accent: "#ea580c",
    accentFg: "white",
    bgLight: "#fff7ed",
    bgDark: "#1c0700",
    textDark: "#1c0700",
    headline: "Transformă-ți corpul. Schimbă-ți viața.",
    tagline: "Echipamente moderne, antrenori certificați, rezultate garantate.",
    services: ["Antrenamente Personalizate", "Clase de Grup", "Nutriție & Suplimente"],
    price: "Abonament de la 150 lei/lună",
    cta: "Prima săptămână gratis",
  },
  {
    slug: "restaurant",
    name: "Restaurant & Cafenea",
    sector: "Servicii Locale",
    emoji: "🍽️",
    accent: "#d97706",
    accentFg: "white",
    bgLight: "#fffbeb",
    bgDark: "#1c0f00",
    textDark: "#1c0f00",
    headline: "Gusturi autentice, momente memorabile.",
    tagline: "Bucătărie tradițională, ingrediente locale, atmosferă unică.",
    services: ["Meniu À La Carte", "Rezervări Private", "Livrare & Catering"],
    price: "Meniu prânz de la 35 lei",
    cta: "Rezervă o masă",
  },
  {
    slug: "hotel",
    name: "Hotel & Cazare",
    sector: "Servicii Locale",
    emoji: "🏨",
    accent: "#7c3aed",
    accentFg: "white",
    bgLight: "#f5f3ff",
    bgDark: "#1e0a3c",
    textDark: "#1e0a3c",
    headline: "Cazare de excepție, experiențe unice.",
    tagline: "Camere elegante, servicii premium și locație centrală.",
    services: ["Camere & Suite", "Mic Dejun Inclus", "Conferințe & Evenimente"],
    price: "Noapte de la 250 lei",
    cta: "Verifică disponibilitatea",
  },
  {
    slug: "imobiliare",
    name: "Agenție Imobiliară",
    sector: "Servicii Locale",
    emoji: "🏠",
    accent: "#475569",
    accentFg: "white",
    bgLight: "#f8fafc",
    bgDark: "#0f172a",
    textDark: "#0f172a",
    headline: "Casa visurilor tale te așteaptă.",
    tagline: "Vindem, cumpărăm și închiriem proprietăți în toată țara.",
    services: ["Vânzare & Cumpărare", "Închirieri Rezidențiale", "Evaluări Imobiliare"],
    price: "Evaluare gratuită",
    cta: "Caută proprietăți",
  },
  {
    slug: "avocatura",
    name: "Cabinet Avocatură",
    sector: "Servicii Locale",
    emoji: "⚖️",
    accent: "#374151",
    accentFg: "white",
    bgLight: "#f9fafb",
    bgDark: "#111827",
    textDark: "#111827",
    headline: "Drepturile tale, apărate cu profesionalism.",
    tagline: "Consultanță juridică, litigii civile și comerciale.",
    services: ["Drept Civil & Comercial", "Litigii & Arbitraj", "Consultanță Juridică"],
    price: "Consultație inițială 200 lei",
    cta: "Programează o consultație",
  },
  {
    slug: "contabilitate",
    name: "Contabilitate",
    sector: "Servicii Locale",
    emoji: "📊",
    accent: "#1e3a5f",
    accentFg: "white",
    bgLight: "#f0f4fa",
    bgDark: "#0a1628",
    textDark: "#0a1628",
    headline: "Finanțele tale, în ordine perfectă.",
    tagline: "Contabilitate, consultanță fiscală și salarizare pentru IMM-uri.",
    services: ["Contabilitate Completă", "Consultanță Fiscală", "Salarizare & HR"],
    price: "De la 300 lei/lună",
    cta: "Solicită o ofertă",
  },
  {
    slug: "constructii",
    name: "Construcții & Renovări",
    sector: "Servicii Locale",
    emoji: "🏗️",
    accent: "#ca8a04",
    accentFg: "white",
    bgLight: "#fefce8",
    bgDark: "#1a1200",
    textDark: "#1a1200",
    headline: "Construim visurile tale, cărămidă cu cărămidă.",
    tagline: "Construcții la cheie, renovări și amenajări interioare.",
    services: ["Construcții Rezidențiale", "Renovări & Reabilitări", "Amenajări Interioare"],
    price: "Deviz gratuit",
    cta: "Solicită deviz",
  },
  {
    slug: "arhitectura",
    name: "Arhitectură & Design",
    sector: "Servicii Locale",
    emoji: "✏️",
    accent: "#292524",
    accentFg: "white",
    bgLight: "#fafaf9",
    bgDark: "#1c1917",
    textDark: "#1c1917",
    headline: "Spații gândite pentru oameni.",
    tagline: "Proiecte arhitecturale, design interior și urbanism.",
    services: ["Proiecte Arhitecturale", "Design Interior", "Autorizații & Avize"],
    price: "Consultație inițială gratuită",
    cta: "Prezintă-ți proiectul",
  },
  {
    slug: "auto",
    name: "Service Auto & Dealer",
    sector: "Servicii Locale",
    emoji: "🚗",
    accent: "#dc2626",
    accentFg: "white",
    bgLight: "#fef2f2",
    bgDark: "#1a0000",
    textDark: "#1a0000",
    headline: "Mașina ta, pe mâini bune.",
    tagline: "Service auto autorizat, piese originale și inspecții ITP.",
    services: ["Service & Reparații", "Inspecție ITP", "Vânzare Mașini Second"],
    price: "Diagnoză de la 50 lei",
    cta: "Programează service",
  },
  {
    slug: "salon-frumusete",
    name: "Salon Frumusețe & SPA",
    sector: "Servicii Locale",
    emoji: "💅",
    accent: "#db2777",
    accentFg: "white",
    bgLight: "#fdf2f8",
    bgDark: "#2d0a1e",
    textDark: "#2d0a1e",
    headline: "Frumusețea ta, definitivată.",
    tagline: "Coafură, manichiură, masaj și tratamente faciale profesionale.",
    services: ["Coafură & Colorare", "Manichiură & Pedichiură", "Masaj & Tratamente SPA"],
    price: "Programare de la 80 lei",
    cta: "Rezervă acum",
  },
  {
    slug: "veterinar",
    name: "Clinică Veterinară",
    sector: "Servicii Locale",
    emoji: "🐾",
    accent: "#15803d",
    accentFg: "white",
    bgLight: "#f0fdf4",
    bgDark: "#052e16",
    textDark: "#052e16",
    headline: "Sănătatea animalului tău, cu grijă.",
    tagline: "Consultații veterinare, vaccinări, chirurgie și produse petshop.",
    services: ["Consultații Veterinare", "Vaccinări & Deparazitare", "Chirurgie & Urgențe"],
    price: "Consultație de la 80 lei",
    cta: "Programează o vizită",
  },

  /* ─── SĂNĂTATE & MEDICAL ───────────────────────────────────────── */
  {
    slug: "clinica-privata",
    name: "Clinică Privată",
    sector: "Sănătate & Medical",
    emoji: "🏥",
    accent: "#0369a1",
    accentFg: "white",
    bgLight: "#f0f9ff",
    bgDark: "#082f49",
    textDark: "#082f49",
    headline: "Medicina modernă, la dispoziția ta.",
    tagline: "Specialități multiple, aparatură de ultimă generație, programări rapide.",
    services: ["Consultații Multidisciplinare", "Imagistică & Laborator", "Spitalizare de Zi"],
    price: "Consultație de la 120 lei",
    cta: "Programează-te online",
  },
  {
    slug: "psihologie",
    name: "Cabinet Psihologie",
    sector: "Sănătate & Medical",
    emoji: "🧠",
    accent: "#6d28d9",
    accentFg: "white",
    bgLight: "#f5f3ff",
    bgDark: "#1e0a3c",
    textDark: "#1e0a3c",
    headline: "Echilibrul mental, cheia succesului.",
    tagline: "Psihoterapie, consiliere și coaching pentru o viață împlinită.",
    services: ["Psihoterapie Individuală", "Terapie de Cuplu", "Consiliere Vocațională"],
    price: "Ședință de la 200 lei",
    cta: "Programează o ședință",
  },
  {
    slug: "fizioterapie",
    name: "Fizioterapie & Recuperare",
    sector: "Sănătate & Medical",
    emoji: "🏃",
    accent: "#0891b2",
    accentFg: "white",
    bgLight: "#ecfeff",
    bgDark: "#083344",
    textDark: "#083344",
    headline: "Recuperează-ți mobilitatea. Trăiești fără durere.",
    tagline: "Fizioterapie, kinetoterapie și recuperare medicală specializată.",
    services: ["Fizioterapie & Kinetoterapie", "Masaj Terapeutic", "Recuperare Post-Traumatică"],
    price: "Evaluare inițială gratuită",
    cta: "Rezervă o programare",
  },
  {
    slug: "nutritie",
    name: "Nutriție & Dietetică",
    sector: "Sănătate & Medical",
    emoji: "🥗",
    accent: "#16a34a",
    accentFg: "white",
    bgLight: "#f0fdf4",
    bgDark: "#052e16",
    textDark: "#052e16",
    headline: "Mănâncă bine. Trăiește mai bine.",
    tagline: "Planuri nutriționale personalizate, susținere continuă și rezultate reale.",
    services: ["Consultație Nutrițională", "Plan Alimentar Personalizat", "Monitorizare & Follow-up"],
    price: "Consultație de la 150 lei",
    cta: "Începe transformarea",
  },
  {
    slug: "optica",
    name: "Optică Medicală",
    sector: "Sănătate & Medical",
    emoji: "👓",
    accent: "#2563eb",
    accentFg: "white",
    bgLight: "#eff6ff",
    bgDark: "#0c1a3a",
    textDark: "#0c1a3a",
    headline: "Vezi lumea mai clar.",
    tagline: "Consultații oftalmologice, ochelari și lentile de contact premium.",
    services: ["Consultație Oftalmologică", "Rame & Lentile Premium", "Lentile de Contact"],
    price: "Consultație gratuită",
    cta: "Programează un test",
  },

  /* ─── EDUCAȚIE & INSTITUȚII ────────────────────────────────────── */
  {
    slug: "scoala",
    name: "Școală Privată",
    sector: "Educație & Instituții",
    emoji: "🎓",
    accent: "#4338ca",
    accentFg: "white",
    bgLight: "#eef2ff",
    bgDark: "#1e1b4b",
    textDark: "#1e1b4b",
    headline: "Educația care formează caractere.",
    tagline: "Curriculum modern, profesori dedicați, mediu sigur și stimulant.",
    services: ["Ciclul Primar & Gimnazial", "Activități Extracurriculare", "Evaluări & Olimpiade"],
    price: "Înscrierea deschisă",
    cta: "Aplică acum",
  },
  {
    slug: "gradinita",
    name: "Grădiniță & After-School",
    sector: "Educație & Instituții",
    emoji: "🌈",
    accent: "#f59e0b",
    accentFg: "black",
    bgLight: "#fffbeb",
    bgDark: "#1c0f00",
    textDark: "#1c0f00",
    headline: "Unde copiii cresc fericiți.",
    tagline: "Program adaptat, activități creative și educație prin joc.",
    services: ["Grădiniță Program Prelungit", "After-School & Teme", "Activități Creative"],
    price: "Taxă de la 800 lei/lună",
    cta: "Înscrie-ți copilul",
  },
  {
    slug: "cursuri",
    name: "Cursuri Online & Offline",
    sector: "Educație & Instituții",
    emoji: "📚",
    accent: "#6d28d9",
    accentFg: "white",
    bgLight: "#f5f3ff",
    bgDark: "#1e0a3c",
    textDark: "#1e0a3c",
    headline: "Investește în tine. Curs cu curs.",
    tagline: "Cursuri profesionale, certificate recunoscute, instructori experți.",
    services: ["Cursuri Online Live", "Module Video On-Demand", "Certificare Internațională"],
    price: "Curs de la 299 lei",
    cta: "Înscrie-te la un curs",
  },
  {
    slug: "universitate",
    name: "Universitate & Academie",
    sector: "Educație & Instituții",
    emoji: "🏛️",
    accent: "#1e3a8a",
    accentFg: "white",
    bgLight: "#eff6ff",
    bgDark: "#0c1a3a",
    textDark: "#0c1a3a",
    headline: "Cunoaștere. Cercetare. Viitor.",
    tagline: "Programe de licență, masterat și doctorat în domenii de actualitate.",
    services: ["Programe de Licență", "Masterat & Doctorat", "Cercetare & Publicații"],
    price: "Admitere deschisă",
    cta: "Aplică pentru admitere",
  },
  {
    slug: "institutii-stat",
    name: "Primărie & Instituții Publice",
    sector: "Educație & Instituții",
    emoji: "🏛️",
    accent: "#1e40af",
    accentFg: "white",
    bgLight: "#eff6ff",
    bgDark: "#0c1a3a",
    textDark: "#0c1a3a",
    headline: "În serviciul comunității.",
    tagline: "Transparență, eficiență și acces rapid la servicii publice.",
    services: ["Servicii Cetățeni Online", "Proiecte & Investiții Locale", "Transparență Decizională"],
    price: "Servicii gratuite",
    cta: "Accesează serviciile",
  },
  {
    slug: "ong",
    name: "ONG & Asociații",
    sector: "Educație & Instituții",
    emoji: "🤝",
    accent: "#059669",
    accentFg: "white",
    bgLight: "#ecfdf5",
    bgDark: "#022c22",
    textDark: "#022c22",
    headline: "Împreună schimbăm lumea.",
    tagline: "Programe sociale, voluntariat și impact real în comunitate.",
    services: ["Programe Sociale", "Voluntariat", "Fundraising & Donații"],
    price: "Implică-te gratuit",
    cta: "Devino voluntar",
  },
  {
    slug: "biblioteca",
    name: "Bibliotecă & Cultură",
    sector: "Educație & Instituții",
    emoji: "📖",
    accent: "#92400e",
    accentFg: "white",
    bgLight: "#fef3c7",
    bgDark: "#1c0f00",
    textDark: "#1c0f00",
    headline: "Cunoașterea e la un raft distanță.",
    tagline: "Împrumuturi, evenimente culturale și acces la resurse digitale.",
    services: ["Împrumut Cărți & Reviste", "Evenimente & Lansări", "Baze de Date Digitale"],
    price: "Acces gratuit",
    cta: "Înscrie-te gratuit",
  },
  {
    slug: "muzeu",
    name: "Muzeu & Galerie de Artă",
    sector: "Educație & Instituții",
    emoji: "🎨",
    accent: "#6b7280",
    accentFg: "white",
    bgLight: "#f9fafb",
    bgDark: "#111827",
    textDark: "#111827",
    headline: "Arta care vorbește. Istoria care trăiește.",
    tagline: "Expoziții permanente, evenimente culturale și ghiduri interactive.",
    services: ["Expoziții Permanente & Temporare", "Ateliere & Workshopuri", "Tururi Ghidate"],
    price: "Bilet de la 15 lei",
    cta: "Planifică o vizită",
  },

  /* ─── TURISM & OSPITALITATE ────────────────────────────────────── */
  {
    slug: "turism",
    name: "Agenție de Turism",
    sector: "Turism & Ospitalitate",
    emoji: "✈️",
    accent: "#0ea5e9",
    accentFg: "white",
    bgLight: "#f0f9ff",
    bgDark: "#082f49",
    textDark: "#082f49",
    headline: "Lumea te așteaptă. Noi te ducem acolo.",
    tagline: "Pachete turistice, city break-uri și vacanțe exotice la prețuri imbatabile.",
    services: ["Vacanțe All-Inclusive", "City Break-uri Europene", "Circuite & Croaziere"],
    price: "Pachet de la 299€/persoană",
    cta: "Explorează destinații",
  },
  {
    slug: "pensiune",
    name: "Pensiune & Vilă",
    sector: "Turism & Ospitalitate",
    emoji: "🏡",
    accent: "#78350f",
    accentFg: "white",
    bgLight: "#fef3c7",
    bgDark: "#1c0f00",
    textDark: "#1c0f00",
    headline: "Liniște, natură și confort autentic.",
    tagline: "Cazare montană, mic dejun inclus și activități în aer liber.",
    services: ["Cazare Comfort & Deluxe", "Mic Dejun & Pensiune Completă", "Activități Outdoor"],
    price: "Noapte de la 180 lei",
    cta: "Verifică disponibilitatea",
  },
  {
    slug: "restaurant-fine",
    name: "Restaurant Fine Dining",
    sector: "Turism & Ospitalitate",
    emoji: "🍷",
    accent: "#881337",
    accentFg: "white",
    bgLight: "#fff1f2",
    bgDark: "#1a0008",
    textDark: "#1a0008",
    headline: "O experiență gastronomică de neuitat.",
    tagline: "Bucătărie fusion, somelier dedicat și atmosferă de excepție.",
    services: ["Meniu Degustare 7 Feluri", "Pairing Vinuri Premium", "Mese Private & Evenimente"],
    price: "Meniu de la 290 lei/persoană",
    cta: "Rezervă o masă",
  },
  {
    slug: "catering",
    name: "Catering & Evenimente",
    sector: "Turism & Ospitalitate",
    emoji: "🎉",
    accent: "#b45309",
    accentFg: "white",
    bgLight: "#fffbeb",
    bgDark: "#1c0f00",
    textDark: "#1c0f00",
    headline: "Evenimentul tău, perfect până la ultimul detaliu.",
    tagline: "Catering pentru nunți, corporate events și petreceri private.",
    services: ["Nunți & Botezuri", "Evenimente Corporate", "Catering la Domiciliu"],
    price: "Ofertă personalizată",
    cta: "Solicită o ofertă",
  },
  {
    slug: "spa-resort",
    name: "SPA & Resort",
    sector: "Turism & Ospitalitate",
    emoji: "🧖",
    accent: "#6d28d9",
    accentFg: "white",
    bgLight: "#f5f3ff",
    bgDark: "#1e0a3c",
    textDark: "#1e0a3c",
    headline: "Relaxare totală. Regenerare completă.",
    tagline: "Tratamente SPA, piscine termale și retreat-uri de wellness.",
    services: ["Tratamente SPA & Masaj", "Piscine & Saune", "Pachete Wellness Weekend"],
    price: "Abonament de la 350 lei/lună",
    cta: "Rezervă un pachet",
  },

  /* ─── TECH & SOFTWARE ──────────────────────────────────────────── */
  {
    slug: "saas",
    name: "SaaS & Software B2B",
    sector: "Tech & Software",
    emoji: "☁️",
    accent: "#2563eb",
    accentFg: "white",
    bgLight: "#eff6ff",
    bgDark: "#0c1a3a",
    textDark: "#0c1a3a",
    headline: "Software care lucrează pentru tine.",
    tagline: "Platformă cloud intuitivă, integrări native și suport 24/7.",
    services: ["Dashboard & Analytics", "Integrări API & Webhooks", "Suport & Onboarding"],
    price: "Plan Starter gratuit",
    cta: "Încearcă gratuit 14 zile",
  },
  {
    slug: "erp",
    name: "ERP & Business Software",
    sector: "Tech & Software",
    emoji: "⚙️",
    accent: "#4338ca",
    accentFg: "white",
    bgLight: "#eef2ff",
    bgDark: "#1e1b4b",
    textDark: "#1e1b4b",
    headline: "Toate procesele tale, într-un singur sistem.",
    tagline: "ERP modular: stocuri, contabilitate, HR, producție și vânzări.",
    services: ["Gestiune Stocuri & Facturare", "Modul HR & Salarizare", "Rapoarte & Business Intelligence"],
    price: "Demo gratuit",
    cta: "Solicită o demonstrație",
  },
  {
    slug: "crm",
    name: "CRM & Sales Platform",
    sector: "Tech & Software",
    emoji: "🤝",
    accent: "#7c3aed",
    accentFg: "white",
    bgLight: "#f5f3ff",
    bgDark: "#1e0a3c",
    textDark: "#1e0a3c",
    headline: "Mai mulți clienți. Mai multe vânzări.",
    tagline: "Gestionează relațiile cu clienții, automatizează follow-up-urile.",
    services: ["Pipeline Vânzări Visual", "Automatizări Email & SMS", "Raportare & Forecast"],
    price: "De la 49€/lună",
    cta: "Testează 30 de zile gratis",
  },
  {
    slug: "aplicatie-mobila",
    name: "Aplicație Mobilă",
    sector: "Tech & Software",
    emoji: "📱",
    accent: "#16a34a",
    accentFg: "white",
    bgLight: "#f0fdf4",
    bgDark: "#052e16",
    textDark: "#052e16",
    headline: "Afacerea ta în buzunarul clientului.",
    tagline: "Aplicații native iOS & Android, PWA și soluții cross-platform.",
    services: ["Aplicații Native iOS & Android", "Aplicații PWA & Hybrid", "UX Design & Testare"],
    price: "Estimare gratuită",
    cta: "Discutăm proiectul",
  },
  {
    slug: "cybersecurity",
    name: "Cybersecurity",
    sector: "Tech & Software",
    emoji: "🔐",
    accent: "#dc2626",
    accentFg: "white",
    bgLight: "#fef2f2",
    bgDark: "#1a0000",
    textDark: "#1a0000",
    headline: "Protejează ceea ce contează.",
    tagline: "Audit de securitate, penetration testing și training angajați.",
    services: ["Audit de Securitate", "Penetration Testing", "SOC & Monitorizare 24/7"],
    price: "Audit de la €990",
    cta: "Auditează-ți sistemele",
  },
  {
    slug: "ai-ml",
    name: "AI & Machine Learning",
    sector: "Tech & Software",
    emoji: "🤖",
    accent: "#8b5cf6",
    accentFg: "white",
    bgLight: "#f5f3ff",
    bgDark: "#1e0a3c",
    textDark: "#1e0a3c",
    headline: "Inteligența artificială la lucru pentru tine.",
    tagline: "Modele ML custom, automatizări AI și soluții de procesare date.",
    services: ["Modele ML & Deep Learning", "Automatizări cu AI", "Procesare NLP & Computer Vision"],
    price: "Proof of concept gratuit",
    cta: "Discutăm cazul tău",
  },
  {
    slug: "agentie-web",
    name: "Agenție Web & Digital",
    sector: "Tech & Software",
    emoji: "💻",
    accent: "#0f172a",
    accentFg: "white",
    bgLight: "#f8fafc",
    bgDark: "#0f172a",
    textDark: "#0f172a",
    headline: "Construim digital care convertește.",
    tagline: "Website-uri, campanii, SEO și marketing digital pentru IMM-uri.",
    services: ["Website & Landing Pages", "SEO & Google Ads", "Social Media & Content"],
    price: "Website de la €990",
    cta: "Obține o ofertă gratuită",
  },
  {
    slug: "it-support",
    name: "IT Support & Managed",
    sector: "Tech & Software",
    emoji: "🛠️",
    accent: "#0369a1",
    accentFg: "white",
    bgLight: "#f0f9ff",
    bgDark: "#082f49",
    textDark: "#082f49",
    headline: "IT-ul tău, în siguranță maximă.",
    tagline: "Suport tehnic, mentenanță sisteme și backup în cloud.",
    services: ["Helpdesk & Suport Remote", "Mentenanță Infrastructură", "Backup & Disaster Recovery"],
    price: "Contract de la 500 lei/lună",
    cta: "Solicită un audit",
  },
  {
    slug: "cloud",
    name: "Cloud & Hosting",
    sector: "Tech & Software",
    emoji: "🌩️",
    accent: "#0284c7",
    accentFg: "white",
    bgLight: "#f0f9ff",
    bgDark: "#082f49",
    textDark: "#082f49",
    headline: "Infrastructură rapidă, scalabilă, sigură.",
    tagline: "Hosting managed, VPS, CDN și soluții cloud enterprise.",
    services: ["Hosting Managed WordPress", "VPS & Server Dedicat", "CDN & SSL Gratuit"],
    price: "Hosting de la 9€/lună",
    cta: "Alege un plan",
  },
  {
    slug: "startup",
    name: "Startup & Scaleup",
    sector: "Tech & Software",
    emoji: "🚀",
    accent: "#ea580c",
    accentFg: "white",
    bgLight: "#fff7ed",
    bgDark: "#1c0700",
    textDark: "#1c0700",
    headline: "De la idee la investiție.",
    tagline: "Accelerator, mentorship, networking și acces la investitori.",
    services: ["Program Accelerator", "Mentorship & Networking", "Pitch Deck & Due Diligence"],
    price: "Aplicație gratuită",
    cta: "Aplică la program",
  },

  /* ─── E-COMMERCE ───────────────────────────────────────────────── */
  {
    slug: "fashion",
    name: "Fashion & Modă",
    sector: "E-Commerce",
    emoji: "👗",
    accent: "#0a0a0a",
    accentFg: "white",
    bgLight: "#fafafa",
    bgDark: "#0a0a0a",
    textDark: "#0a0a0a",
    headline: "Stilul tău. Livrăm perfecțiunea.",
    tagline: "Colecții exclusiviste, branduri premium și livrare rapidă.",
    services: ["Femei, Bărbați & Copii", "Branduri Internaționale", "Returnare Gratuită 30 Zile"],
    price: "Livrare gratuită la 200+ lei",
    cta: "Cumpără acum",
  },
  {
    slug: "electronice",
    name: "Electronice & Gadgets",
    sector: "E-Commerce",
    emoji: "📱",
    accent: "#1d4ed8",
    accentFg: "white",
    bgLight: "#eff6ff",
    bgDark: "#0a0f1e",
    textDark: "#0a0f1e",
    headline: "Tehnologia viitorului, azi.",
    tagline: "Smartphone-uri, laptopuri, tablete și accesorii la prețuri competitive.",
    services: ["Cele Mai Noi Modele", "Garanție Extinsă Inclusă", "Rate Fără Dobândă"],
    price: "Telefoane de la 999 lei",
    cta: "Explorează ofertele",
  },
  {
    slug: "mobila",
    name: "Mobilă & Decorațiuni",
    sector: "E-Commerce",
    emoji: "🛋️",
    accent: "#92400e",
    accentFg: "white",
    bgLight: "#fef3c7",
    bgDark: "#1c0f00",
    textDark: "#1c0f00",
    headline: "Casa ta, redesenată.",
    tagline: "Mobilă de calitate, decorațiuni și soluții complete de interior.",
    services: ["Mobilă Cameră & Living", "Decorațiuni & Iluminat", "Consultanță Design Gratuit"],
    price: "Livrare și montaj inclus",
    cta: "Configurează spațiul",
  },
  {
    slug: "cosmetice",
    name: "Cosmetice & Parfumuri",
    sector: "E-Commerce",
    emoji: "💄",
    accent: "#db2777",
    accentFg: "white",
    bgLight: "#fdf2f8",
    bgDark: "#2d0a1e",
    textDark: "#2d0a1e",
    headline: "Frumusețea ta, amplificată.",
    tagline: "Cosmetice naturale, parfumuri originale și produse de îngrijire premium.",
    services: ["Make-up & Îngrijire Ten", "Parfumuri Originale", "Produse BIO & Naturale"],
    price: "Livrare gratuită la 150+ lei",
    cta: "Descoperă colecția",
  },
  {
    slug: "alimentar",
    name: "Alimentar, Bio & Organic",
    sector: "E-Commerce",
    emoji: "🥦",
    accent: "#15803d",
    accentFg: "white",
    bgLight: "#f0fdf4",
    bgDark: "#052e16",
    textDark: "#052e16",
    headline: "Sănătos, local, autentic.",
    tagline: "Produse bio, lactate de fermă, legume proaspete și produse tradiționale.",
    services: ["Legume & Fructe Bio", "Lactate & Ouă de Fermă", "Produse Tradiționale"],
    price: "Coșul săptămânal de la 99 lei",
    cta: "Compune coșul tău",
  },
  {
    slug: "bijuterii",
    name: "Bijuterii & Ceasuri",
    sector: "E-Commerce",
    emoji: "💍",
    accent: "#d4af6a",
    accentFg: "black",
    bgLight: "#fefce8",
    bgDark: "#0a0806",
    textDark: "#0a0806",
    headline: "Bijuterii care spun povestea ta.",
    tagline: "Aur, argint, diamante și ceasuri elvețiene pentru momente speciale.",
    services: ["Bijuterii Aur & Argint", "Ceasuri Elvețiene", "Gravuri Personalizate"],
    price: "Bijuterie de la 200 lei",
    cta: "Alege bijuteria perfectă",
  },
  {
    slug: "sport-ecomm",
    name: "Sport & Outdoor",
    sector: "E-Commerce",
    emoji: "⛰️",
    accent: "#c2410c",
    accentFg: "white",
    bgLight: "#fff7ed",
    bgDark: "#1c0700",
    textDark: "#1c0700",
    headline: "Echipat pentru orice provocare.",
    tagline: "Echipament sportiv, outdoor gear și articole fitness premium.",
    services: ["Îmbrăcăminte & Încălțăminte Sport", "Echipament Outdoor & Camping", "Fitness & Nutriție Sportivă"],
    price: "Reduceri până la 40%",
    cta: "Shop Sport",
  },
  {
    slug: "artizanat",
    name: "Artizanat & Handmade",
    sector: "E-Commerce",
    emoji: "🏺",
    accent: "#c2410c",
    accentFg: "white",
    bgLight: "#fff7ed",
    bgDark: "#1c0700",
    textDark: "#1c0700",
    headline: "Creat cu mâinile. Ales cu inima.",
    tagline: "Ceramică, textile, bijuterii artizanale și obiecte decorative unice.",
    services: ["Ceramică & Olărit", "Textile & Macramé", "Bijuterii Artizanale"],
    price: "Piese de la 50 lei",
    cta: "Descoperă artizanii",
  },

  /* ─── CREATIV & MEDIA ──────────────────────────────────────────── */
  {
    slug: "fotografie",
    name: "Studio Foto & Video",
    sector: "Creativ & Media",
    emoji: "📷",
    accent: "#0a0a0a",
    accentFg: "white",
    bgLight: "#fafafa",
    bgDark: "#0a0a0a",
    textDark: "#0a0a0a",
    headline: "Imaginile care rămân în timp.",
    tagline: "Fotografie de eveniment, publicitate și videografie profesională.",
    services: ["Fotografie Nuntă & Eveniment", "Publicitate & Product Shot", "Videografie & Reels"],
    price: "Pachet de la 500 lei",
    cta: "Discută proiectul tău",
  },
  {
    slug: "muzica",
    name: "Studio Muzical & Artist",
    sector: "Creativ & Media",
    emoji: "🎵",
    accent: "#6d28d9",
    accentFg: "white",
    bgLight: "#f5f3ff",
    bgDark: "#1e0a3c",
    textDark: "#1e0a3c",
    headline: "Muzica ta, la nivel profesional.",
    tagline: "Înregistrări, mixaj, masterizare și producție muzicală.",
    services: ["Studio Recording", "Mixaj & Masterizare", "Producție & Beatmaking"],
    price: "Sesiune de la 150 lei/oră",
    cta: "Rezervă o sesiune",
  },
  {
    slug: "gaming",
    name: "Gaming & Esports",
    sector: "Creativ & Media",
    emoji: "🎮",
    accent: "#00ff88",
    accentFg: "black",
    bgLight: "#f0fff8",
    bgDark: "#040810",
    textDark: "#040810",
    headline: "GG. EVERY DAY.",
    tagline: "Echipă esports, turnee, streaming și comunitate de gameri.",
    services: ["Echipă Competitivă", "Turnee & Ligi", "Streaming & Content"],
    price: "Membership de la 0 lei",
    cta: "JOIN THE TEAM",
  },
  {
    slug: "agentie-creativa",
    name: "Agenție Creativă",
    sector: "Creativ & Media",
    emoji: "🎨",
    accent: "#e879f9",
    accentFg: "white",
    bgLight: "#fdf4ff",
    bgDark: "#1a0a1e",
    textDark: "#1a0a1e",
    headline: "Creativitate fără limite.",
    tagline: "Branding, design grafic, copywriting și campanii vizuale.",
    services: ["Identitate Vizuală & Branding", "Design Print & Digital", "Campanii Creative 360°"],
    price: "Brief gratuit",
    cta: "Trimite un brief",
  },
  {
    slug: "podcast",
    name: "Podcast & Media Online",
    sector: "Creativ & Media",
    emoji: "🎙️",
    accent: "#f97316",
    accentFg: "white",
    bgLight: "#fff7ed",
    bgDark: "#1c0700",
    textDark: "#1c0700",
    headline: "Vocea ta. Audiența ta.",
    tagline: "Producție podcast, distribuție pe toate platformele și promovare.",
    services: ["Producție & Editare Podcast", "Distribuție Spotify & Apple", "Promovare & Creștere Audiență"],
    price: "Pachet pilot de la 299 lei",
    cta: "Lansează podcastul",
  },
  {
    slug: "design-grafic",
    name: "Studio Design Grafic",
    sector: "Creativ & Media",
    emoji: "✏️",
    accent: "#ec4899",
    accentFg: "white",
    bgLight: "#fdf2f8",
    bgDark: "#2d0a1e",
    textDark: "#2d0a1e",
    headline: "Design care vorbește fără cuvinte.",
    tagline: "Logo, branding, materiale print și design digital profesional.",
    services: ["Logo & Identitate Vizuală", "Materiale Marketing Print", "Design Social Media"],
    price: "Logo de la 299 lei",
    cta: "Solicită un brief",
  },

  /* ─── INDUSTRIE & PRODUCȚIE ────────────────────────────────────── */
  {
    slug: "productie",
    name: "Producție & Manufactura",
    sector: "Industrie & Producție",
    emoji: "🏭",
    accent: "#374151",
    accentFg: "white",
    bgLight: "#f9fafb",
    bgDark: "#111827",
    textDark: "#111827",
    headline: "Calitate fabricată în România.",
    tagline: "Producție la comandă, serii mici și industriale pentru export.",
    services: ["Producție la Comandă", "Control Calitate ISO", "Livrare Internă & Export"],
    price: "Ofertă la cerere",
    cta: "Solicită o ofertă",
  },
  {
    slug: "agricultura",
    name: "Agricultură & Ferme",
    sector: "Industrie & Producție",
    emoji: "🌾",
    accent: "#65a30d",
    accentFg: "white",
    bgLight: "#f7fee7",
    bgDark: "#1a2e05",
    textDark: "#1a2e05",
    headline: "Pământul bun dă roade bune.",
    tagline: "Produse agricole proaspete, ferme certificate și livrare directă.",
    services: ["Cereale & Leguminoase", "Legume & Fructe de Sezon", "Produse Animaliere"],
    price: "Contact direct producător",
    cta: "Contactează fermierul",
  },
  {
    slug: "logistica",
    name: "Transport & Logistică",
    sector: "Industrie & Producție",
    emoji: "🚛",
    accent: "#1e3a5f",
    accentFg: "white",
    bgLight: "#f0f4fa",
    bgDark: "#0a1628",
    textDark: "#0a1628",
    headline: "Livrăm oriunde. Livram la timp.",
    tagline: "Transport rutier, distribuție națională și soluții logistice complete.",
    services: ["Transport Marfă Național", "Distribuție Last-Mile", "Depozitare & Fulfilment"],
    price: "Ofertă transport la cerere",
    cta: "Solicită o cotație",
  },
  {
    slug: "energie",
    name: "Energie & Panouri Solare",
    sector: "Industrie & Producție",
    emoji: "☀️",
    accent: "#f59e0b",
    accentFg: "black",
    bgLight: "#fffbeb",
    bgDark: "#1c0f00",
    textDark: "#1c0f00",
    headline: "Energia verde care îți reduce facturile.",
    tagline: "Panouri fotovoltaice, instalare și monitorizare pentru case și firme.",
    services: ["Instalare Panouri Fotovoltaice", "Baterii de Stocare", "Monitorizare & Service"],
    price: "Instalare de la 4.999€",
    cta: "Calculează economia",
  },
];

export function getCategoryBySlug(slug: string): TemplateCategory | undefined {
  return categories.find((c) => c.slug === slug);
}

export const sectorOrder: Sector[] = [
  "Servicii Locale",
  "Sănătate & Medical",
  "Educație & Instituții",
  "Turism & Ospitalitate",
  "Tech & Software",
  "E-Commerce",
  "Creativ & Media",
  "Industrie & Producție",
];
